<a href="https://colab.research.google.com/github/kshitizkool/Data-Analytics-Assignments/blob/main/Chi_Square_Test_for_Relationship_of_Categorical_Variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chi-Square Test for Categorical Variables

In [1]:
import scipy.stats as stats
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('/content/ChiSqare.csv', encoding='latin-1')

In [3]:
data.head(5)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       76 non-null     int64  
 1   Gender                   76 non-null     object 
 2   Classification           76 non-null     object 
 3   Height                   76 non-null     float64
 4   Shoe Size                76 non-null     float64
 5   Phone Time               75 non-null     float64
 6   # of Shoes               75 non-null     float64
 7   Birth order              76 non-null     object 
 8   Pets                     75 non-null     float64
 9   Happy                    74 non-null     float64
 10  Funny                    73 non-null     float64
 11  College                  76 non-null     object 
 12  Bfast Calories           74 non-null     float64
 13  Exercise                 76 non-null     int64  
 14  Stat Pre                 75 

In [4]:
Contigency=pd.crosstab(data['Political'],data['College'])
print(Contigency)

College      Education  Liberal Arts  Natural Sciences  Nursing  \
Political                                                         
Democrat             3             1                17        4   
Independent          0             3                13        5   
Republican           5             4                 9        1   

College      Undergraduate Studies  
Political                           
Democrat                         3  
Independent                      4  
Republican                       4  


In [5]:
Contigency.values 

array([[ 3,  1, 17,  4,  3],
       [ 0,  3, 13,  5,  4],
       [ 5,  4,  9,  1,  4]])

In [6]:
#Observed Values
Observed_Values = Contigency.values
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[ 3  1 17  4  3]
 [ 0  3 13  5  4]
 [ 5  4  9  1  4]]


In [7]:
val=stats.chi2_contingency(Contigency)
print(type(val))
val

<class 'tuple'>


(11.619615891355021,
 0.16899955816578377,
 8,
 array([[ 2.94736842,  2.94736842, 14.36842105,  3.68421053,  4.05263158],
        [ 2.63157895,  2.63157895, 12.82894737,  3.28947368,  3.61842105],
        [ 2.42105263,  2.42105263, 11.80263158,  3.02631579,  3.32894737]]))

In [8]:
Expected=val[3]
Expected

array([[ 2.94736842,  2.94736842, 14.36842105,  3.68421053,  4.05263158],
       [ 2.63157895,  2.63157895, 12.82894737,  3.28947368,  3.61842105],
       [ 2.42105263,  2.42105263, 11.80263158,  3.02631579,  3.32894737]])

In [13]:
print(Contigency.shape)
no_of_rows=Contigency.shape[0]
no_of_columns=Contigency.shape[1]
dof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:",dof)
alpha = 0.05

(3, 5)
Degree of Freedom: 8


In [16]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected)])
print(chi_square[1])
chi_square_statistic=chi_square[0]+chi_square[1]
print("chi-square statistic:",chi_square_statistic)
critical_value=chi2.ppf(q=1-alpha,df=dof)
print('critical_value:',critical_value)

2.3679813664596274
chi-square statistic: 7.7476397515527955
critical_value: 15.50731305586545


In [15]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Retain H0,There is no relationship between 2 categorical variables
